---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
options(width = 100)
```

# redq

## Empirical Dynamic Quantiles for Time Series

A semi-vectorised parallel-looped algorithm for computing empirical dynamic quantiles for large temporal data sets.

## Installation

You could install the package from Github using

```{r gh-install, eval = FALSE}
# install.packages("remotes")
remotes::install_github("szmsu2011/redq")
```

## Usage

```{r example}
library(redq)
library(purrr)
library(tidyr)

set.seed(2023)
arima_data <- map(seq_len(500), \(x) {
  arima.sim(list(ar = c(.95, -.1)), 100, mean = x / 500 - .5)
}) |>
  set_names(sprintf("ts%s", seq_len(500))) |>
  as_tibble()

(edq_data <- edq(arima_data, c(.25, .5, .75)))
```

```{r plot, fig.height = 3, message = FALSE}
library(dplyr)
library(ggplot2)

arima_data |>
  mutate(time = seq_len(nrow(arima_data))) |>
  pivot_longer(starts_with("ts")) |>
  ggplot(aes(time, value, group = name)) +
  geom_line() +
  geom_line(
    aes(col = name),
    data = edq_data |>
      mutate(time = seq_len(nrow(arima_data))) |>
      pivot_longer(starts_with("q_"))
  ) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "")
```
